# sudo: required
# dist: trusty
image: ablu/ubuntu-texlive-full:latest
before_script:
- apt-get update
# - apt-get install git texlive-full
- apt-get install git
- mkdir -p /usr/share/fonts/opentype
- git clone https://github.com/a20185/adobefonts
- cd adobefonts
- cp *.otf /usr/share/fonts/opentype
- mkfontscale
- mkfontdir
- fc-cache -fv

stages:
- test

test_build:
  stage: test
  script:
  - make
  - echo ls /builds/