# sudo: required
# dist: trusty
image: ablu/ubuntu-texlive-full:latest
before_script:
- apt-get update
# - apt-get install git texlive-full
- apt-get install -y git language-pack-zh-hans language-pack-zh-hant 
- mkdir -p /usr/share/fonts/opentype
- git clone https://github.com/a20185/adobefonts
- cd adobefonts
- cp *.otf /usr/share/fonts/opentype
# - mkfontscale
# - mkfontdir
- fc-cache -f -v

stages:
- test

test_build:
  stage: test
  script:
  - cd ..
  - make
  - echo ls /builds/