# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Compile
        run: |
          apt-get update -y
          apt-get install --no-install-recommends -y make fonts-arphic-ukai fonts-noto-cjk-extra
          make pdf -C presentation
          make pdf
          mv main.pdf main.fandol.pdf
          sed -i  's| fontset=fandol,| fontset=ubuntu,|' sysuthesis.cls
          make pdf
          mv main.pdf main.ubuntu.pdf
          mv presentation/pre.pdf pre.pdf

      - uses: actions/upload-artifact@v3
        with:
          path: |
            main.*.pdf
            pre.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            main.*.pdf
            pre.pdf
